# Generated by Django 3.0.8 on 2020-07-19 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('create_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complete', models.BooleanField()),
                ('claimed', models.BooleanField()),
                ('last_modify', models.DateTimeField(auto_now=True)),
                ('claim_worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CollectiveRedditArchiver.Worker')),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CollectiveRedditArchiver.Subreddit')),
            ],
        ),
    ]
